server:
  port: 9099
spring:
  redis:
    ##redis 单机环境配置 # 主从配置与单机相同
    #    host: 127.0.0.1
    #    port: 6379
    password:
    database: 0 # 连接哪个数据库
    ssl: false #启用SSL终端识别
    ##redis 集群环境配置
    cluster:
      nodes: 192.168.136.132:6381,192.168.136.132:6382,192.168.136.132:6383,192.168.136.132:6384,192.168.136.132:6385,192.168.136.132:6386
      commandTimeout: 5000  #设置命令的执行时间，如果超过这个时间，则报错;
      max-redirects: 3  # 获取失败 最大重定向次数
    #    sentinel: #配置哨兵
    #      nodes: # 节点
    #      master: # 主
    jedis:
      pool:
        max-active: 300 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 100 #最大空闲连接
        min-idle: 20 #连接池的最小空闲连接
    timeout: 6000s #连接超时时间
redisCluster:
  ports: 192.168.136.132:6381,192.168.136.132:6382,192.168.136.132:6383